"""ORM model for user-saved ``few_shot`` examples.

These are code samples the operator has flagged as "good examples" —
later the prompt builder will pull 1-2 of them into the system prompt
based on prompt similarity. Single-user project, no auth, no ownership.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column
from ulid import ULID

from app.db.session import Base


def _new_ulid() -> str:
    return str(ULID())


class FewShot(Base):
    """A user-curated example (prompt + code + style) for future retrieval."""

    __tablename__ = "few_shots"

    id: Mapped[str] = mapped_column(String(26), primary_key=True, default=_new_ulid)

    # The user request that produced this code.
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    # Full Manim code (from ``from manim import *`` onward).
    code: Mapped[str] = mapped_column(Text, nullable=False)
    # Which style was active when the code was generated.
    style: Mapped[str] = mapped_column(String(20), nullable=False)

    # One-sentence description of what the animation shows. Generated by
    # an LLM at save time so future RAG retrieval has a stable, summarised
    # target instead of the raw user prompt (which varies in phrasing).
    # Required now — the POST endpoint generates it before insert.
    summary: Mapped[str] = mapped_column(Text, nullable=False)

    # Provenance: which conversation + which assistant message did this come from.
    # Nullable so we can ingest curated samples from outside the app later
    # (e.g. seed scripts) without faking conversation IDs.
    source_conversation_id: Mapped[str | None] = mapped_column(
        String(26),
        ForeignKey("conversations.id", ondelete="SET NULL"),
        nullable=True,
    )
    source_message_id: Mapped[str | None] = mapped_column(
        String(26), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        Index("ix_few_shots_style", "style"),
        Index("ix_few_shots_created_at", "created_at"),
    )

    __all__ = ["FewShot"]


__all__ = ["FewShot"]
