"""Storage helpers for the ``few_shots`` table.

Single-user project — no ownership / no auth. The table is a flat pool
of "good examples" the prompt builder will later draw from.
"""
from __future__ import annotations

from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Session

from app.db.models import FewShot


async def create_few_shot(
    session: AsyncSession,
    *,
    prompt: str,
    code: str,
    summary: str,
    style: str,
    source_conversation_id: Optional[str] = None,
    source_message_id: Optional[str] = None,
) -> FewShot:
    """Insert a new curated example.

    ``summary`` is required — it should already have been generated by
    ``summarise_few_shot`` at the call site so we don't pay the LLM
    latency inside the storage layer.
    """
    row = FewShot(
        prompt=prompt.strip(),
        code=code.strip(),
        summary=summary.strip(),
        style=style,
        source_conversation_id=source_conversation_id,
        source_message_id=source_message_id,
    )
    session.add(row)
    await session.commit()
    await session.refresh(row)
    return row


async def list_few_shots(
    session: AsyncSession,
    *,
    style: Optional[str] = None,
    limit: int = 50,
) -> list[FewShot]:
    """Most recent first. Optional ``style`` filter."""
    stmt = select(FewShot).order_by(FewShot.created_at.desc()).limit(limit)
    if style:
        stmt = stmt.where(FewShot.style == style)
    result = await session.execute(stmt)
    return list(result.scalars().all())


# ---------------------------------------------------------------------------
# Sync variants — for unit tests that drive the table via a plain Session.
# ---------------------------------------------------------------------------

def _create_few_shot_sync(
    session: Session,
    *,
    prompt: str,
    code: str,
    summary: str,
    style: str,
    source_conversation_id: Optional[str] = None,
    source_message_id: Optional[str] = None,
) -> FewShot:
    row = FewShot(
        prompt=prompt.strip(),
        code=code.strip(),
        summary=summary.strip(),
        style=style,
        source_conversation_id=source_conversation_id,
        source_message_id=source_message_id,
    )
    session.add(row)
    session.commit()
    session.refresh(row)
    return row


def _list_few_shots_sync(
    session: Session,
    *,
    style: Optional[str] = None,
    limit: int = 50,
) -> list[FewShot]:
    stmt = select(FewShot).order_by(FewShot.created_at.desc()).limit(limit)
    if style:
        stmt = stmt.where(FewShot.style == style)
    return list(session.execute(stmt).scalars().all())


__all__ = [
    "create_few_shot",
    "list_few_shots",
    "_create_few_shot_sync",
    "_list_few_shots_sync",
]
