"""Validate Manim code generated by the LLM.

Returns (ok, error_message). Used as a guard before handing code off to the
renderer.
"""
from __future__ import annotations

import ast
import re

REQUIRED_IMPORT = "from manim import *"

DANGEROUS_PATTERNS: list[str] = [
    r"\bopen\s*\(",                       # file open
    r"\b(os\.|sys\.|subprocess\.|shutil\.)",  # system calls
    r"\b(requests|urllib|http)\.",        # network
    r"\b(eval|exec|compile)\s*\(",        # dynamic exec
    r"while\s+True\s*:",                  # infinite loop
]

# LLM 思路草稿泄漏到代码注释里。注释行匹配 — 多行模式。
# Manim 教学动画里几乎不会出现这种自然注释，命中几乎一定是
# coder 没清掉自己的 chain-of-thought。
COT_LEAK_PATTERNS: list[str] = [
    r"^\s*#\s*Hmm\b",
    r"^\s*#\s*Actually,?\s+(?:let me|I|we)\b",
    r"^\s*#\s*OK,?\s*let me\b",
    r"^\s*#\s*Let me\s+(?:rethink|restart|try|show)\b",
    r"^\s*#\s*(?:Simpler approach|Better:|Lemme)\b",
    r"^\s*#\s*Wait,?\s+this\s+(?:might|is)\b",
]


def validate_code(code: str) -> tuple[bool, str]:
    """Validate LLM-generated Manim code. Returns (ok, error_message)."""
    # 1. Required import
    if REQUIRED_IMPORT not in code:
        return False, "missing required import: from manim import *"

    # 2. Dangerous patterns
    for pattern in DANGEROUS_PATTERNS:
        if re.search(pattern, code):
            return False, f"dangerous pattern detected: {pattern}"

    # 3. LLM 思路草稿泄漏 — 注释行级检测。
    for pattern in COT_LEAK_PATTERNS:
        if re.search(pattern, code, re.MULTILINE):
            return False, f"chain-of-thought leaked into comments: {pattern}"

    # 4. AST parse
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return False, f"syntax error: {e}"

    # 5. Scene subclass with construct()
    has_scene = any(
        isinstance(node, ast.ClassDef)
        and any(
            isinstance(base, ast.Name) and base.id == "Scene"
            for base in node.bases
        )
        and any(
            isinstance(child, ast.FunctionDef) and child.name == "construct"
            for child in node.body
        )
        for node in ast.walk(tree)
    )
    if not has_scene:
        return False, "no Scene subclass with construct() found"

    return True, ""


def extract_scene_name(code: str) -> str | None:
    """Return the first Scene subclass name found in code, or None."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and any(
            isinstance(base, ast.Name) and base.id == "Scene"
            for base in node.bases
        ):
            return node.name
    return None
